AllCops:
 Exclude:
   # You could specify set of files or dirs while you want to be ignored by rubocop
   - 'vendor/**/*'
   - 'spec/**/*'
   - 'config/**/*'
   - 'db/**/*'
   - 'bin/*'
   - 'Gemfile'
   - 'Gemfile.lock'
   - 'Rakefile'
   - 'Guardfile'
Documentation:
  Enabled: false
Lint/UnneededCopDisableDirective:
  Enabled: false
Metrics/LineLength:
  Max: 100
Style/FrozenStringLiteralComment:
  Enabled: false
Rails:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/MethodLength:
  Max: 8
Metrics/ClassLength:
  Max: 120
Style/SymbolArray:
  Enabled: true
Style/Alias:
  EnforcedStyle: prefer_alias_method
